export const CITY_BOUNDS = Object.freeze({
  minX: -10.7,
  maxX: 10.7,
  minZ: -52,
  maxZ: 52,
});

export const BUILDING_SLOTS = Object.freeze([
  {
    id: 'mori-pharmacy',
    label: 'MORI',
    localLabel: '薬 局',
    sublabel: 'NIGHT PHARMACY',
    side: -1,
    position: [-17.35, 0, 26],
    size: [11.5, 25.5, 47],
    material: 'concrete',
    accent: 0x36d7cf,
    secondary: 0xe05c62,
    seed: 3109,
    profile: 'apartments',
    shops: ['open', 'shutter', 'pharmacy', 'open', 'shutter'],
  },
  {
    id: 'kuroda-works',
    label: 'KURODA',
    localLabel: '黒 田',
    sublabel: 'OPTICS + REPAIR',
    side: -1,
    position: [-17.35, 0, -26],
    size: [11.5, 32.5, 47],
    material: 'brick',
    accent: 0xd65574,
    secondary: 0x6bb7c7,
    seed: 8421,
    profile: 'workshop',
    shops: ['shutter', 'repair', 'open', 'shutter', 'repair'],
  },
  {
    id: 'nami-eatery',
    label: 'NAMI',
    localLabel: '波',
    sublabel: 'LATE KITCHEN',
    side: 1,
    position: [17.35, 0, 26],
    size: [11.5, 28.5, 47],
    material: 'brick',
    accent: 0xe88946,
    secondary: 0x51b9b2,
    seed: 1193,
    profile: 'tenement',
    shops: ['eatery', 'open', 'shutter', 'eatery', 'open'],
  },
  {
    id: 'echo-capsules',
    label: 'ECHO',
    localLabel: '睡 眠',
    sublabel: 'CAPSULE ROOMS',
    side: 1,
    position: [17.35, 0, -26],
    size: [11.5, 35, 47],
    material: 'concreteDark',
    accent: 0x62a9ba,
    secondary: 0xd56e8f,
    seed: 6677,
    profile: 'capsules',
    shops: ['laundry', 'shutter', 'open', 'laundry', 'shutter'],
  },
]);

export const STREET_SIGNS = Object.freeze([
  { title: 'LOWER WARD', subtitle: 'SERVICE LANE 03', local: '下 層 区' },
  { title: 'MIDNIGHT', subtitle: 'FOOD + TEA', local: '夜 食' },
  { title: 'ECHO', subtitle: 'VACANCY', local: '空 室' },
]);
